name: Build Docker Image

on:
  push:
    branches: [ "main" ]

jobs:

  build_and_publish_image:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to ghcr.io
      run: echo $GITHUB_TOKEN | docker login ghcr.io -u lippesola --password-stdin
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/lippesola/lama-api:nightly
    - name: Push the Docker image
      run: docker push ghcr.io/lippesola/lama-api:nightly
